apiVersion: v1
kind: Secret
metadata:
  name: api
  namespace: golang101
type: Opaque
data:
  DB_DSN: aG9zdD1wb3N0Z3Jlcy5nb2xhbmcxMDEuc3ZjLmNsdXN0ZXIubG9jYWwgdXNlcj1nb2xhbmcxMDEgcGFzc3dvcmQ9Z29sYW5nMTAxcGFzcyBkYm5hbWU9Z29sYW5nMTAxIHNzbG1vZGU9ZGlzYWJsZQ==
  REDIS_ADDR: cmVkaXMuZ29sYW5nMTAxLnN2Yy5jbHVzdGVyLmxvY2FsOjYzNzk=
  REDIS_PASSWORD: ""
