apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: golang101
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api
          image: api
          ports:
            - containerPort: 8080
          envFrom:
            - secretRef:
                name: api